### ISSUE TITLE
Home Directory Assumption

### ISSUE THREAD

**Issue by pfrank13** [ryanmaclean/Mac-Pro-1-1-El-Capitan-Upgrades#2]
#1 The postinstall.sh script assumes it's copying the boot.efi file from the user's home directory but when it fetches the boot efi zip it puts it in the current directory.  It probably should pull boot.efi from the current directory.

**Comment by pfrank13** [comment]
I provided a pull request here #1

**Comment by ryanmaclean** [comment]
All fixed up, thanks again for the PR!
